2023-11-28 15:42:11 INFO     Logging Module Started
2023-11-28 15:42:11 INFO     State Machine: init_state
2023-11-28 15:42:11 INFO     websocketClient: Connected to Server: <socket.socket fd=456, family=2, type=1, proto=0, laddr=('127.0.0.1', 5211), raddr=('127.0.0.1', 65432)>
2023-11-28 15:42:13 ERROR    reportingClient: Caught Connection Error, restarting
Traceback (most recent call last):
  File "C:\Users\dheard\Documents\0000-python\adam-controller\reportingClient.py", line 35, in reportingClient
    s.connect((HOST, PORT))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2023-11-28 15:42:15 INFO     State Machine: wait_state
2023-11-28 15:47:46 ERROR    commandClient: Caught Connection Error, restarting
Traceback (most recent call last):
  File "C:\Users\dheard\Documents\0000-python\adam-controller\commandClient.py", line 40, in commandClient
    data = s.recv(1024)
           ^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
